package com.example.icetea.models;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.firebase.firestore.CollectionReference;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.ListenerRegistration;
import com.google.firebase.firestore.Query;
import com.google.firebase.firestore.QuerySnapshot;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Singleton class for managing notifications in Firestore.
 * <p>
 * Provides methods to retrieve, add, and listen to notifications for users.
 * All operations are asynchronous and rely on Firestore callbacks.
 * </p>
 */
public class NotificationDB {

    /** Singleton instance */
    private static NotificationDB instance;

    /** Reference to the 'notifications' collection in Firestore */
    private final CollectionReference notificationCollection;

    /**
     * Private constructor initializing the Firestore collection reference.
     */
    public NotificationDB() {
        FirebaseFirestore db = FirebaseFirestore.getInstance();
        notificationCollection = db.collection("notifications");
    }

    /**
     * Gets the singleton instance of NotificationDB.
     * If no instance exists, one is created. Subsequent calls return the same instance.
     *
     * @return the singleton NotificationDB instance
     */
    public static NotificationDB getInstance() {
        if (instance == null) {
            instance = new NotificationDB();
        }
        return instance;
    }

    /**
     * Retrieves all notifications for a specific user from Firestore.
     * Notifications are ordered by timestamp in descending order (most recent first).
     * <p>
     * This is an asynchronous operation; results are delivered via the provided listener.
     * </p>
     *
     * @param userId   the ID of the user whose notifications to retrieve
     * @param listener the OnCompleteListener callback that handles the query result
     */
    public void getNotificationsForUser(String userId, OnCompleteListener<QuerySnapshot> listener) {
        notificationCollection
                .whereEqualTo("userId", userId)
                .orderBy("timestamp", Query.Direction.DESCENDING)
                .get()
                .addOnCompleteListener(listener);
    }

    /**
     * Adds a new notification document to the Firestore collection.
     * <p>
     * A new document ID is automatically generated by Firestore.
     * This is an asynchronous operation; the result is delivered via the provided listener.
     * </p>
     *
     * @param notification the Notification object to add to Firestore
     * @param listener     the OnCompleteListener callback that handles the operation result
     */
    public void addNotification(Notification notification, OnCompleteListener<Void> listener) {
        notificationCollection.document()
                .set(notification)
                .addOnCompleteListener(listener);
    }

    /**
     * Sets up a real-time listener for notifications of a specific user.
     * <p>
     * Whenever the user's notifications are updated in Firestore, the provided
     * callback is invoked with the updated list.
     * </p>
     *
     * @param userId   the ID of the user to listen for
     * @param callback callback invoked on updates with a list of notifications
     * @return the ListenerRegistration object which can be used to remove the listener
     */
    public ListenerRegistration listenNotificationsForUser(String userId, NotificationsCallback callback) {
        return notificationCollection
                .whereEqualTo("userId", userId)
                .orderBy("timestamp", Query.Direction.DESCENDING)
                .addSnapshotListener((querySnapshot, e) -> {
                    if (e != null || querySnapshot == null) return;
                    List<Notification> notifications = querySnapshot.toObjects(Notification.class);
                    callback.onUpdate(notifications);
                });
    }

    /**
     * Callback interface for receiving updates when notifications change in Firestore.
     */
    public interface NotificationsCallback {
        /**
         * Called when the list of notifications is updated.
         *
         * @param notifications the updated list of notifications
         */
        void onUpdate(List<Notification> notifications);
    }
}