package com.example.icetea.entrant;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.firestore.CollectionReference;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.Query;
import com.google.firebase.firestore.QuerySnapshot;

import java.util.HashMap;
import java.util.Map;

/**
 * Database service for managing Notification documents in Firestore.
 *It handles querying
 * notifications for specific users and adding new notifications to the database.
 * @author AVYAAN
 * @version 1.0
 */
public class NotificationDB {
    private static NotificationDB instance;
    private final CollectionReference notificationCollection;

    /**
     * Private constructor to prevent direct instantiation.
     * Initializes the Firestore collection reference to the "Notification" collection.
     */
    public NotificationDB() {
        FirebaseFirestore db = FirebaseFirestore.getInstance();
        notificationCollection = db.collection("Notification");
    }

    /**
     * Gets the singleton instance of NotificationDB.
     * If no instance exists, one is created. Subsequent calls return the same instance.
     * @return the singleton NotificationDB instance
     */
    public static NotificationDB getInstance() {
        if (instance == null) {
            instance = new NotificationDB();
        }
        return instance;
    }

    /**
     * Retrieves all notifications for a specific user from Firestore.
     * Notifications are ordered by timestamp in descending order (most recent first).
     * This is an asynchronous operation; results are delivered via the provided listener.
     * @param userId the ID of the user whose notifications to retrieve
     * @param listener the OnCompleteListener callback that handles the query result
     */
    public void getNotificationsForUser(String userId, OnCompleteListener<QuerySnapshot> listener) {
        notificationCollection
                .whereEqualTo("userId", userId)
                .orderBy("timestamp", Query.Direction.DESCENDING)
                .get()
                .addOnCompleteListener(listener);
    }

    /**
     * Adds a new notification document to the Firestore collection.
     * A new document ID is automatically generated by Firestore. This is an
     * asynchronous operation; the result is delivered via the provided listener.
     * @param notification the Notification object to add to Firestore
     * @param listener the OnCompleteListener callback that handles the operation result
     */
    public void addNotification(Notification notification, OnCompleteListener<Void> listener) {
        notificationCollection.document()
                .set(notification)
                .addOnCompleteListener(listener);
    }

    /**
     * Updates the status of a notification (accept/decline).
     * @param notificationId the Firestore document ID of the notification
     * @param status the new status: "accepted" or "declined"
     * @param listener the OnCompleteListener callback that handles the operation result
     */
    public void updateNotificationStatus(String notificationId, String status, OnCompleteListener<Void> listener) {
        Map<String, Object> updates = new HashMap<>();
        updates.put("status", status);

        notificationCollection.document(notificationId)
                .update(updates)
                .addOnCompleteListener(listener);
    }
}